### ISSUE TITLE
releases page blank

### ISSUE THREAD

**Issue by mhornsby** [gjr80/weewx-aurora#1]
Hi 

Just letting you know releases page is not setup 

Installation using the wee_extension utility
Download the latest Aurora extension from the Aurora extension **releases page** into a directory accessible from the weeWX machine.

**Comment by gjr80** [comment]
Long time coming but extension packages for the Aurora driver and PVOutput uploader have been published to the Releases page. `readme.txt` within each package has correct `wee_extension` install instructions, ignore the repo readme for now, will get it updated shortly.
