### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by rimassmd** [gjr80/weewx-aurora#8]
how to connect not via "port" o TCP address

**Comment by gjr80** [comment]
My aurora driver will not connect via TCP as it stands now. I am guessing, but I expect it could be modified to work much like the WeeWX vantage driver which can handle both serial and TCP connections.  The best approach would likely be (as with the vantage driver) to pull the open/close/write/read port methods out of the driver and into their own class. You could have one class for serial comms and one for TCP with the driver using the appropriate class depending on a driver config option.

This is not something I have time to do nor would I be able to test it. Feel free though to fork the repo and have a go yourself.

**Comment by gjr80** [comment]
Marking complete due to age and no action
